version: '3.8'

services:
  browsely.modules.dispatcher.api:
    image: browsely-dispatcher-api
    container_name: Browsely.Dispatcher.Api
    build:
      context: .
      dockerfile: src/Modules/Dispatcher/Browsely.Modules.Dispatcher.Api/Dockerfile
    ports:
      - "5163:5163"
      - "8081:8080"
    depends_on:
      - browsely.rabbitmq
      - browsely.sqlserver
      - browsely.seq

  browsely.modules.node.api:
    image: browsely-node-api
    container_name: Browsely.Node.Api
    build:
      context: .
      dockerfile: src/Modules/Node/Browsely.Modules.Node.Api/Dockerfile
    ports:
      - "5058:5058"
      - "8082:8080"
    privileged: true
    depends_on:
      - browsely.rabbitmq

  browsely.modules.node.api.2:
    image: browsely-node-api
    container_name: Browsely.Node.Api.2
    build:
      context: .
      dockerfile: src/Modules/Node/Browsely.Modules.Node.Api/Dockerfile
    ports:
      - "5059:5058"
      - "8083:8080"
    privileged: true
    depends_on:
      - browsely.rabbitmq

  browsely.modules.node.api.3:
    image: browsely-node-api
    container_name: Browsely.Node.Api.3
    build:
      context: .
      dockerfile: src/Modules/Node/Browsely.Modules.Node.Api/Dockerfile
    ports:
      - "5060:5058"
      - "8084:8080"
    privileged: true
    depends_on:
      - browsely.rabbitmq

  browsely.rabbitmq:
    container_name: Browsely.Rabbitmq
    image: bitnami/rabbitmq:latest
    restart: unless-stopped
    environment:
      - RABBITMQ_PASSWORD=NewPassword123
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit loopback_users []
    ports:
      - "15672:15672"
      - "5672:5672"

  browsely.sqlserver:
    container_name: Browsely.SqlServer
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Plavi.12.
    ports:
      - "1434:1433"
    volumes:
      - ./data/sqldata:/var/opt/mssql/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Plavi.12. -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  browsely.seq:
    container_name: Browsely.Seq
    restart: unless-stopped
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "88:80"
      - "5341:5341"
    volumes:
      - ./data/seq:/data
